name: Security and Build and Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep:
    name: Semgrep Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Semgrep using pip
        run: |
          pip install semgrep

      - name: Run Semgrep Security Audit
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_TOKEN }}
        run: |
          semgrep --config "p/security-audit" --output semgrep-security-audit-report.json
          
      - name: Run Semgrep Secrets Scan
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_TOKEN }}
        run: |
          semgrep --config "p/secrets" --output semgrep-secrets-scan-report.json
          
      - name: Run Semgrep CI Scan
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_TOKEN }}
        run: |
          semgrep --config "p/ci" --output semgrep-ci-scan-report.json

      - name: Upload Semgrep Reports as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-reports
          path: |
            semgrep-security-audit-report.json
            semgrep-secrets-scan-report.json
            semgrep-ci-scan-report.json

  checkov:
    name: Checkov Security Scan
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Checkov
        run: |
          pip install checkov

      - name: Run Checkov on Infrastructure Code
        run: |
          checkov -d ./infra \
            --framework terraform,kubernetes,cloudformation \
            --output json \
            --output-file checkov-report.json \
            --skip-check BC.PipelineMissing

      - name: Upload Checkov Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: checkov-reports
          path: checkov-report.json
  
  docker-build-push:
    name: Docker Build and Push to Docker Hub
    runs-on: ubuntu-latest
    needs: [semgrep, checkov]  # Ensures this job runs after the security scans
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}  # Using the commit SHA as the image tag
          echo "Building Docker image for application: ${{ secrets.DOCKER_HUB_APPLICATION }} with tag: $IMAGE_TAG"
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_APPLICATION }}:$IMAGE_TAG .
        
      - name: Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          echo "Pushing Docker image for application: ${{ secrets.DOCKER_HUB_APPLICATION }} with tag: $IMAGE_TAG"
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_APPLICATION }}:$IMAGE_TAG
